In [1]:
## Preloads
using Statistics
using FFTW
using Plots
using BenchmarkTools
using Profile
using LinearAlgebra
using Measures
using HDF5
push!(LOAD_PATH, pwd())
using DHC_2DUtils
using MLDatasets
using Images
theme(:juno)
using DSP
using Interpolations
using Distributed
using ProgressMeter
using ImageTransformations

  likely near /n/home12/saydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:162
  likely near /n/home12/saydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:162
  likely near /n/home12/saydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:166
  likely near /n/home12/saydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:166
  likely near /n/home12/saydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:176
  likely near /n/home12/saydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:179
  likely near /n/home12/saydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:181
  likely near /n/home12/saydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:184
  likely near /n/home12/saydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:186
  likely near /n/home12/saydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:189
  likely near /n/home12/saydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:203
  likely near /n/home12/saydjari/.julia/packages/Plots

In [3]:
test_img = rand(64,64)

64×64 Array{Float64,2}:
 0.0868411  0.305192   0.000551469  …  0.32376    0.50245    0.253099 
 0.936534   0.777647   0.787261        0.494642   0.716906   0.237628 
 0.354839   0.391009   0.736443        0.734436   0.244077   0.235471 
 0.617686   0.940411   0.304766        0.486898   0.189678   0.869187 
 0.669646   0.602532   0.999187        0.13492    0.172022   0.332099 
 0.302903   0.493309   0.875714     …  0.698646   0.359424   0.982819 
 0.295067   0.773514   0.490432        0.0567048  0.013576   0.100118 
 0.960455   0.928083   0.607701        0.938393   0.845784   0.436998 
 0.737326   0.859642   0.759201        0.841363   0.461628   0.373866 
 0.677785   0.128748   0.348029        0.722469   0.188893   0.155674 
 0.744752   0.217661   0.368901     …  0.878485   0.732765   0.169981 
 0.907712   0.647553   0.00132128      0.916439   0.461178   0.310507 
 0.296062   0.928457   0.316319        0.39061    0.511243   0.182726 
 ⋮                                  ⋱                

In [4]:
imresize(test_img,Dims((128,128)),Lanczos4OpenCV())

128×128 Array{Float64,2}:
 0.0868411  0.189811  0.339589  0.18844   …   0.477978   0.346874   0.253099 
 0.326579   0.442228  0.546616  0.350889      0.607472   0.42318    0.297739 
 0.831363   0.928342  0.866306  0.662344      0.71867    0.452804   0.291174 
 0.887021   0.917519  0.747641  0.709641      0.561615   0.300758   0.167188 
 0.512287   0.504469  0.396859  0.539965      0.288879   0.175085   0.12558  
 0.300776   0.358976  0.429976  0.517809  …   0.204654   0.389622   0.434004 
 0.479394   0.646372  0.840545  0.696525      0.312889   0.743803   0.831678 
 0.715418   0.898617  1.0405    0.805036      0.328267   0.700661   0.755233 
 0.725234   0.811598  0.788934  0.718006      0.23264    0.380554   0.376573 
 0.59563    0.591829  0.47573   0.620422      0.339085   0.470885   0.454709 
 0.407954   0.407638  0.379259  0.610482  …   0.538492   0.875712   0.902069 
 0.213414   0.287378  0.456019  0.652443      0.392366   0.804953   0.871503 
 0.190283   0.338357  0.630236  0.7138

In [5]:
imrotate(test_img,0.3,axes(test_img), Lanczos4OpenCV())

64×64 Array{Float64,2}:
 NaN         NaN         NaN         …  NaN         NaN         NaN       
 NaN         NaN         NaN            NaN         NaN         NaN       
 NaN         NaN         NaN            NaN         NaN         NaN       
 NaN         NaN         NaN            NaN         NaN         NaN       
 NaN         NaN         NaN            NaN         NaN         NaN       
 NaN         NaN         NaN         …  NaN         NaN         NaN       
 NaN         NaN         NaN            NaN         NaN         NaN       
 NaN         NaN         NaN            NaN         NaN         NaN       
 NaN         NaN         NaN              0.734863    0.389493  NaN       
 NaN         NaN         NaN              0.704157    0.565225    0.821177
 NaN         NaN         NaN         …    0.740625    0.742674    0.211872
 NaN         NaN         NaN              0.428783    0.768344    0.572968
 NaN         NaN         NaN              0.944959    0.110106    0.688327
 

In [2]:
workers()

1-element Array{Int64,1}:
 1

In [3]:
addprocs(30)

30-element Array{Int64,1}:
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
  ⋮
 20
 21
 22
 23
 24
 25
 26
 27
 28
 29
 30
 31

In [4]:
M = 100
angle_array = []
for i = 2π/M:2π/M:2π
    append!(angle_array,i)
end

M = 100
train_angles = [2π/M,π/3,2π/3,3π/3,4π/3,5π/3];

In [5]:
train_x, train_y = MNIST.traindata()
test_x, test_y   = MNIST.testdata()

lst_train = Array{Any}(undef, 0)
for i = 1:60000
    push!(lst_train,train_x[:,:,i])
end


lst_test = Array{Any}(undef, 0)
for i = 1:10000
    push!(lst_test,test_x[:,:,i])
end

In [10]:
@everywhere begin
    using Statistics
    using BenchmarkTools
    using LinearAlgebra
    using Distributed
    using ProgressMeter
    push!(LOAD_PATH, pwd())
    using DHC_2DUtils
    using FFTW
    using MLDatasets
    using Images
    using Interpolations
    using ImageTransformations
    
    # filter bank
    filter_hash = fink_filter_hash(1,8,nx=256,wd=2,pc=1)
    
    function mnist_pad(im; θ=0.0)
        impad = zeros(Float64,128,128)
        impad[78:-1:51,51:78] = im'
        imbig = imresize(impad,(256,256))
        if θ != 0.0
            imrot = imrotate(imbig, θ, axes(imbig), Lanczos4OpenCV())
            imrot[findall(imrot .!= imrot)] .= 0.0
            return imrot
        end
        return imbig
    end
    
    function mnist_DHC(params)
        θ, x = params
        image    = mnist_pad(x[:,:], θ=θ)
        WST = DHC_compute(image, filter_hash)
        return WST
    end
    
end
 
mnist_DHC_out = @showprogress pmap(mnist_DHC, Iterators.product(angle_array,lst_test))
mnist_DHC_out = hcat(mnist_DHC_out...)

h5write("mnist_DHC_test_ang_LanRot.h5", "data", mnist_DHC_out, deflate=3)
h5write("mnist_DHC_test_ang_LanRot.h5", "angles", angle_array, deflate=3)

mnist_DHC_out = @showprogress pmap(mnist_DHC, Iterators.product(train_angles,lst_train))
mnist_DHC_out = hcat(mnist_DHC_out...)

h5write("mnist_DHC_train_ang_LanRot.h5", "data", mnist_DHC_out, deflate=3)
h5write("mnist_DHC_train_ang_LanRot.h5", "angles", train_angles, deflate=3)

Progress: 100%|█████████████████████████████████████████| Time: 4:00:54


MethodError: MethodError: no method matching datatype(::Array{Any,1})
Closest candidates are:
  datatype(!Matched::HDF5.Attribute) at /n/home12/saydjari/.julia/packages/HDF5/d0V7K/src/HDF5.jl:1017
  datatype(!Matched::HDF5.Dataset) at /n/home12/saydjari/.julia/packages/HDF5/d0V7K/src/HDF5.jl:1015
  datatype(!Matched::Union{Bool, Float32, Float64, Int16, Int32, Int64, Int8, UInt16, UInt32, UInt64, UInt8, HDF5.Reference}) at /n/home12/saydjari/.julia/packages/HDF5/d0V7K/src/HDF5.jl:1020
  ...

In [6]:
h5write("mnist_DHC_test_ang_LanRot.h5", "angles", convert(Array{Float64},angle_array), deflate=3)

In [7]:
@everywhere begin
    using Statistics
    using BenchmarkTools
    using LinearAlgebra
    using Distributed
    using ProgressMeter
    push!(LOAD_PATH, pwd())
    using DHC_2DUtils
    using FFTW
    using MLDatasets
    using Images
    using Interpolations
    using ImageTransformations
    
    # filter bank
    filter_hash = fink_filter_hash(1,8,nx=256,wd=2,pc=1)
    
    function mnist_pad(im; θ=0.0)
        impad = zeros(Float64,128,128)
        impad[78:-1:51,51:78] = im'
        imbig = imresize(impad,(256,256))
        if θ != 0.0
            imrot = imrotate(imbig, θ, axes(imbig), Lanczos4OpenCV())
            imrot[findall(imrot .!= imrot)] .= 0.0
            return imrot
        end
        return imbig
    end
    
    function mnist_DHC(params)
        θ, x = params
        image    = mnist_pad(x[:,:], θ=θ)
        WST = DHC_compute(image, filter_hash)
        return WST
    end
    
end
 

mnist_DHC_out = @showprogress pmap(mnist_DHC, Iterators.product(train_angles,lst_train))
mnist_DHC_out = hcat(mnist_DHC_out...)

h5write("mnist_DHC_train_ang_LanRot.h5", "data", mnist_DHC_out, deflate=3)
h5write("mnist_DHC_train_ang_LanRot.h5", "angles", convert(Array{Float64},train_angles), deflate=3)

Progress: 100%|█████████████████████████████████████████| Time: 1:16:19


In [8]:
train_x, train_y = CIFAR10.traindata();
test_x, test_y   = CIFAR10.testdata();

In [9]:
function color_convert(array, color1, color2)
    chan_img = channelview(array)
    cv = colorview(color1, StackedView(array[:,:,1],array[:,:,2],array[:,:,3]))
    y_im = color2.(cv)
    channels = permutedims(channelview(float.(y_im)),(2,3,1))
    return channels
end

color_convert (generic function with 1 method)

In [13]:
lst_train = Array{Any}(undef, 0)
for i = 1:size(train_x)[4]
    push!(lst_train,train_x[:,:,:,i])
end

lst_test = Array{Any}(undef, 0)
for i = 1:size(test_x)[4]
    push!(lst_test,test_x[:,:,:,i])
end

In [ ]:
@everywhere begin    
    push!(LOAD_PATH,pwd())
    using DHC_2DUtils
    using Profile
    using BenchmarkTools
    using FFTW
    using Test
    using SparseArrays
    using Statistics
    using Plots
    using LinearAlgebra
    using Measures
    using Plots
    using MLDatasets
    using ImageCore
    using Colors
    using AbstractFFTs
    using Interpolations
    using DSP
    using StatsBase
    using Distributed
    using Images
    using ProgressMeter
    
    filter_hash = fink_filter_hash(1, 8, nx=128, pc=1, wd=2)

    function wind_2d(nx)
        dx   = nx/2-1
        filter = zeros(Float64, nx, nx)
        A = DSP.tukey(nx, 0.3)
        itp = extrapolate(interpolate(A,BSpline(Linear())),0)
        @inbounds for x = 1:nx
            sx = x-dx-1    # define sx,sy so that no fftshift() needed
            for y = 1:nx
                sy = y-dx-1
                r  = sqrt.((sx).^2 + (sy).^2) + nx/2
                filter[x,y] = itp(r)
            end
        end
        return filter
    end

    function wind_2d_RGB(nx)
        dx   = nx/2-1
        filter = zeros(Float64, nx, nx)
        A = DSP.tukey(nx, 0.3)
        itp = extrapolate(interpolate(A,BSpline(Linear())),0)
        @inbounds for x = 1:nx
            sx = x-dx-1    # define sx,sy so that no fftshift() needed
            for y = 1:nx
                sy = y-dx-1
                r  = sqrt.((sx).^2 + (sy).^2) + nx/2
                filter[x,y] = itp(r)
            end
        end
        return reshape(filter,nx,nx,1)
    end

    function cifar_pad_RGB(im; θ=0.0)
        imbig = imresize(convert(Array{Float64,3},im),(64,64,3),Lanczos4OpenCV())
        datad_w = fweights(wind_2d(64));
        mu_imbig = zeros(1,1,3)
        for chan = 1:3
            mu_imbig[chan] = mean(imbig[:,:,chan],datad_w)
        end
        imbig .-= mu_imbig
        imbig .*= wind_2d_RGB(64)
        impad = zeros(Float64,128,128,3)
        impad[96:-1:33,33:96,:] = imbig

        if θ != 0.0
            imrot = imrotate(impad, θ, axes(impad), Lanczos4OpenCV())
            imrot[findall(imrot .!= imrot)] .= 0.0
            return imrot .+ mu_imbig
        end

        return impad.+ mu_imbig
    end

    function cifar_DHC(x)
        image = cifar_pad_RGB(x[:,:,:], θ=0.0)
        WST = DHC_compute_RGB(image, filter_hash)
        return WST
    end
end
 
cifar_DHC_out = @showprogress pmap(cifar_DHC, lst_train)
cifar_DHC_out = hcat(cifar_DHC_out...)

h5write("cifar10_RGB_lanczos.h5", "train_data", cifar_DHC_out, deflate=3)
h5write("cifar10_RGB_lanczos.h5", "train_labels", train_y, deflate=3)
h5write("cifar10_RGB_lanczos.h5", "test_labels", test_y, deflate=3)

cifar_DHC_out = @showprogress pmap(cifar_DHC, lst_test)
cifar_DHC_out = hcat(cifar_DHC_out...)

h5write("cifar10_RGB_lanczos.h5", "test_data", cifar_DHC_out, deflate=3)

Progress:  68%|███████████████████████████▉             |  ETA: 0:13:47

In [ ]:
train_x, train_y = CIFAR100.traindata();
test_x, test_y   = CIFAR100.testdata();

In [ ]:
lst_train = Array{Any}(undef, 0)
for i = 1:size(train_x)[4]
    push!(lst_train,train_x[:,:,:,i])
end

lst_test = Array{Any}(undef, 0)
for i = 1:size(test_x)[4]
    push!(lst_test,test_x[:,:,:,i])
end

In [ ]:
@everywhere begin    
    push!(LOAD_PATH,pwd())
    using DHC_2DUtils
    using Profile
    using BenchmarkTools
    using FFTW
    using Test
    using SparseArrays
    using Statistics
    using Plots
    using LinearAlgebra
    using Measures
    using Plots
    using MLDatasets
    using ImageCore
    using Colors
    using AbstractFFTs
    using Interpolations
    using DSP
    using StatsBase
    using Distributed
    using Images
    using ProgressMeter
    
    filter_hash = fink_filter_hash(1, 8, nx=128, pc=1, wd=2)

    function wind_2d(nx)
        dx   = nx/2-1
        filter = zeros(Float64, nx, nx)
        A = DSP.tukey(nx, 0.3)
        itp = extrapolate(interpolate(A,BSpline(Linear())),0)
        @inbounds for x = 1:nx
            sx = x-dx-1    # define sx,sy so that no fftshift() needed
            for y = 1:nx
                sy = y-dx-1
                r  = sqrt.((sx).^2 + (sy).^2) + nx/2
                filter[x,y] = itp(r)
            end
        end
        return filter
    end

    function wind_2d_RGB(nx)
        dx   = nx/2-1
        filter = zeros(Float64, nx, nx)
        A = DSP.tukey(nx, 0.3)
        itp = extrapolate(interpolate(A,BSpline(Linear())),0)
        @inbounds for x = 1:nx
            sx = x-dx-1    # define sx,sy so that no fftshift() needed
            for y = 1:nx
                sy = y-dx-1
                r  = sqrt.((sx).^2 + (sy).^2) + nx/2
                filter[x,y] = itp(r)
            end
        end
        return reshape(filter,nx,nx,1)
    end

    function cifar_pad_RGB(im; θ=0.0)
        imbig = imresize(convert(Array{Float64,3},im),(64,64,3),Lanczos4OpenCV())
        datad_w = fweights(wind_2d(64));
        mu_imbig = zeros(1,1,3)
        for chan = 1:3
            mu_imbig[chan] = mean(imbig[:,:,chan],datad_w)
        end
        imbig .-= mu_imbig
        imbig .*= wind_2d_RGB(64)
        impad = zeros(Float64,128,128,3)
        impad[96:-1:33,33:96,:] = imbig

        if θ != 0.0
            imrot = imrotate(impad, θ, axes(impad), Lanczos4OpenCV())
            imrot[findall(imrot .!= imrot)] .= 0.0
            return imrot .+ mu_imbig
        end

        return impad.+ mu_imbig
    end

    function cifar_DHC(x)
        image = cifar_pad_RGB(x[:,:,:], θ=0.0)
        WST = DHC_compute_RGB(image, filter_hash)
        return WST
    end
end
 
cifar_DHC_out = @showprogress pmap(cifar_DHC, lst_train)
cifar_DHC_out = hcat(cifar_DHC_out...)

h5write("cifar100_RGB_lanczos.h5", "train_data", cifar_DHC_out, deflate=3)
h5write("cifar100_RGB_lanczos.h5", "train_labels", train_y, deflate=3)
h5write("cifar100_RGB_lanczos.h5", "test_labels", test_y, deflate=3)

cifar_DHC_out = @showprogress pmap(cifar_DHC, lst_test)
cifar_DHC_out = hcat(cifar_DHC_out...)

h5write("cifar100_RGB_lanczos.h5", "test_data", cifar_DHC_out, deflate=3)

In [ ]:
@everywhere begin
    using Statistics
    using LinearAlgebra
    using Distributed
    push!(LOAD_PATH,pwd())
    using DHC_2DUtils
    using FFTW
    using Images
    using Interpolations
    using DSP
    using ProgressMeter
    
    # filter bank
    filter_hash = fink_filter_hash(1,8,nx=128,wd=2)
    
    function wind_2d(nx)
        dx   = nx/2-1
        filter = zeros(Float64, nx, nx)
        A = DSP.tukey(nx, 0.3)
        itp = extrapolate(interpolate(A,BSpline(Linear())),0)
        @inbounds for x = 1:nx
            sx = x-dx-1    # define sx,sy so that no fftshift() needed
            for y = 1:nx
                sy = y-dx-1
                r  = sqrt.((sx).^2 + (sy).^2) + nx/2
                filter[x,y] = itp(r)
            end
        end
        return filter
    end
    
    function mnist_pad(im; θ=0.0)
        imbig = imresize(im,(64,64),Lanczos4OpenCV())
        mu_imbig = mean(imbig)
        imbig .-= mu_imbig
        imbig .*= wind_2d(64)
        impad = zeros(Float64,128,128)
        impad[96:-1:33,33:96] = imbig

        if θ != 0.0
            imrot = imrotate(impad, θ, axes(impad), Lanczos4OpenCV())
            imrot[findall(imrot .!= imrot)] .= 0.0
            return imrot .+ mu_imbig
        end

        return impad.+ mu_imbig
    end
    
    function mnist_DHC(x)
        image    = mnist_pad(x[:,:], θ=0.0)
        WST = DHC_compute(image, filter_hash,filter_hash)
        return WST
    end
end
 
mnist_DHC_out = @showprogress pmap(mnist_DHC, lst_train)
mnist_DHC_out = hcat(mnist_DHC_out...)

h5write("cifar100_lanczos.h5", "train_data", mnist_DHC_out, deflate=3)
h5write("cifar100_lanczos.h5", "train_labels", train_y, deflate=3)
h5write("cifar100_lanczos.h5", "test_labels", test_y, deflate=3)

mnist_DHC_out = @showprogress pmap(mnist_DHC, lst_test)
mnist_DHC_out = hcat(mnist_DHC_out...)

h5write("cifar100_lanczos.h5", "train_data", mnist_DHC_out, deflate=3)

In [ ]:
train_x, train_y = CIFAR10.traindata();
test_x, test_y   = CIFAR10.testdata();

In [ ]:
lst_train = Array{Any}(undef, 0)
for i = 1:size(train_x)[4]
    push!(lst_train,train_x[:,:,:,i])
end

lst_test = Array{Any}(undef, 0)
for i = 1:size(test_x)[4]
    push!(lst_test,test_x[:,:,:,i])
end

In [ ]:
@everywhere begin
    using Statistics
    using LinearAlgebra
    using Distributed
    push!(LOAD_PATH,pwd())
    using DHC_2DUtils
    using FFTW
    using Images
    using Interpolations
    using DSP
    using ProgressMeter
    
    # filter bank
    filter_hash = fink_filter_hash(1,8,nx=128,wd=2)
    
    function wind_2d(nx)
        dx   = nx/2-1
        filter = zeros(Float64, nx, nx)
        A = DSP.tukey(nx, 0.3)
        itp = extrapolate(interpolate(A,BSpline(Linear())),0)
        @inbounds for x = 1:nx
            sx = x-dx-1    # define sx,sy so that no fftshift() needed
            for y = 1:nx
                sy = y-dx-1
                r  = sqrt.((sx).^2 + (sy).^2) + nx/2
                filter[x,y] = itp(r)
            end
        end
        return filter
    end
    
    function mnist_pad(im; θ=0.0)
        imbig = imresize(im,(64,64),Lanczos4OpenCV())
        mu_imbig = mean(imbig)
        imbig .-= mu_imbig
        imbig .*= wind_2d(64)
        impad = zeros(Float64,128,128)
        impad[96:-1:33,33:96] = imbig

        if θ != 0.0
            imrot = imrotate(impad, θ, axes(impad), Lanczos4OpenCV())
            imrot[findall(imrot .!= imrot)] .= 0.0
            return imrot .+ mu_imbig
        end

        return impad.+ mu_imbig
    end
    
    function mnist_DHC(x)
        image    = mnist_pad(x[:,:], θ=0.0)
        WST = DHC_compute(image, filter_hash,filter_hash)
        return WST
    end
end
 
mnist_DHC_out = @showprogress pmap(mnist_DHC, lst_train)
mnist_DHC_out = hcat(mnist_DHC_out...)

h5write("cifar10_lanczos.h5", "train_data", mnist_DHC_out, deflate=3)
h5write("cifar10_lanczos.h5", "train_labels", train_y, deflate=3)
h5write("cifar10_lanczos.h5", "test_labels", test_y, deflate=3)

mnist_DHC_out = @showprogress pmap(mnist_DHC, lst_test)
mnist_DHC_out = hcat(mnist_DHC_out...)

h5write("cifar10_lanczos.h5", "train_data", mnist_DHC_out, deflate=3)